sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-1.7.18
notifications:
  irc:
    - "irc.freenode.net#sensu"
addons:
  code_climate:
    repo_token: 767b23081fd38d849be07cd85ade8b06120135f8f983b1c7ead44f2ef0272f6d
